version: 2.0
workflows:
  version: 2
  do_stuff:
  jobs:
    test:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: The First Step
            command: gradle test
        - store_test_results:
            path: build/test-results
        - run:
            name: Build artifact
            command: gradle jar
        - store_artifacts:
            path: build/libs
            destination: prefix
    package:
        requires:
          - test
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run:
              name: Build artifact
              command: gradle jar
          - store_artifacts:
              path: build/libs
              destination: prefix